name: Bump formula

env:
  HOMEBREW_NO_REQUIRE_TAP_TRUST: 1

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  bump:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Bump Homebrew formula
        uses: dawidd6/action-homebrew-bump-formula@v7
        with:
          token: ${{ secrets.HOMEBREW_BUMP_TOKEN }}
          tap: NanamiNakano/homebrew-gpoc
          formula: globalprotect-openconnect
          livecheck: true
